source 'http://rubygems.org'

gem 'sinatra'
gem 'sinatra-content-for'
gem 'git', :git => 'https://github.com/haruyama/ruby-git.git'
gem 'bluecloth'
gem 'rubypants'
# gem 'redcarpet'
gem 'shotgun'
gem 'thin'
